# Generated by Django 5.1.5 on 2026-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The natural language question submitted by staff.')),
                ('generated_sql', models.TextField(blank=True, help_text='The generated Microsoft SQL Server T-SQL query.', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Plain English explanation of the query.')),
                ('detected_domain', models.CharField(blank=True, help_text='Banking domain classification.', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Security Blocked'), ('ERROR', 'Execution Error'), ('CHIT_CHAT', 'Chit Chat / Info')], default='SUCCESS', max_length=20)),
                ('execution_time_ms', models.FloatField(default=0.0, help_text='Pipeline execution latency in milliseconds.')),
                ('rows_count', models.IntegerField(default=0, help_text='Number of preview rows returned.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution or validation failed.', null=True)),
                ('staff_role', models.CharField(default='Analyst', help_text='Role clearance of the user.', max_length=50)),
                ('database_name', models.CharField(blank=True, help_text='Target database where query ran.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query History Record',
                'verbose_name_plural': 'Query History Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label or title for the query.', max_length=200)),
                ('question', models.TextField(help_text='The natural language question.')),
                ('sql', models.TextField(help_text='The verified T-SQL query.')),
                ('category', models.CharField(default='General', help_text='Category or domain.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Query',
                'verbose_name_plural': 'Saved Queries',
                'ordering': ['category', 'title'],
            },
        ),
    ]
